name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: version to publish
        required: true
      otp:
        description: one time password
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 18

      - name: configure git
        run: |
          git config --global user.name 'Romain Prignon'
          git config --global user.email 'pro.rprignon@gmail.com'

      - name: install
        run: npm ci

      - name: version
        run: npm run version:${{ github.event.inputs.version }}

      - name: deploy
        run: npm run deploy -- --otp ${{ github.event.inputs.otp }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
